const MAIN = {
  SET : 'MAIN_SET',
}

// CODE: Journal

const JOURNAL = {
  SEND   : {
    FETCH      : 'JOURNAL_SEND_FETCH',
    CREATE     : 'JOURNAL_SEND_CREATE',
    MODIFY     : 'JOURNAL_SEND_MODIFY',
    ACTIVATE   : 'JOURNAL_SEND_ACTIVATE',
    DEACTIVATE : 'JOURNAL_SEND_DEACTIVATE',
  },
  SAVE   : {
    REPLACE    : 'JOURNAL_SAVE_FETCH',
    ADDTOP     : 'JOURNAL_SAVE_CREATE',
    ADDBOTTOM  : 'JOURNAL_SAVE_CREATE',
    MODIFY     : 'JOURNAL_SAVE_MODIFY',
    DEACTIVATE : 'JOURNAL_SAVE_DEACTIVATE',
    ACTIVATE   : 'JOURNAL_SAVE_ACTIVATE',
  },
  STATUS : {
    SUCCESS : 'JOURNAL_STATUS_SUCCESS',
    REQUEST : 'JOURNAL_STATUS_REQUEST',
    FAILED  : 'JOURNAL_STATUS_FAILED',
  },
}

// CODE: Account

const ACCOUNT = {
  SEND   : {
    FETCH      : 'ACCOUNT_SEND_FETCH',
    CREATE     : 'ACCOUNT_SEND_CREATE',
    MODIFY     : 'ACCOUNT_SEND_MODIFY',
    REPLACE    : 'ACCOUNT_SEND_REPLACE',
    ACTIVATE   : 'ACCOUNT_SEND_ACTIVATE',
    DEACTIVATE : 'ACCOUNT_SEND_DEACTIVATE',
    REMOVE     : 'ACCOUNT_SEND_REMOVE',
  },
  SAVE   : {
    REPLACE    : 'ACCOUNT_SAVE_FETCH',
    ADDTOP     : 'ACCOUNT_SAVE_CREATE',
    MODIFY     : 'ACCOUNT_SAVE_MODIFY',
    DEACTIVATE : 'ACCOUNT_SAVE_DEACTIVATE',
    ACTIVATE   : 'ACCOUNT_SAVE_ACTIVATE',
    REMOVE     : 'ACCOUNT_SAVE_CREATE',
  },
  STATUS : {
    SUCCESS : 'ACCOUNT_STATUS_SUCCESS',
    REQUEST : 'ACCOUNT_STATUS_REQUEST',
    FAILED  : 'ACCOUNT_STATUS_FAILED',
  },
}

// CODE: Branch

const BRANCH = {
  SEND   : {
    FETCH      : 'BRANCH_SEND_FETCH',
    CREATE     : 'BRANCH_SEND_CREATE',
    MODIFY     : 'BRANCH_SEND_MODIFY',
    REPLACE    : 'BRANCH_SEND_REPLACE',
    ACTIVATE   : 'BRANCH_SEND_ACTIVATE',
    DEACTIVATE : 'BRANCH_SEND_DEACTIVATE',
    REMOVE     : 'BRANCH_SEND_REMOVE',
  },
  SAVE   : {
    REPLACE    : 'BRANCH_SAVE_FETCH',
    ADDTOP     : 'BRANCH_SAVE_CREATE',
    MODIFY     : 'BRANCH_SAVE_MODIFY',
    DEACTIVATE : 'BRANCH_SAVE_DEACTIVATE',
    ACTIVATE   : 'BRANCH_SAVE_ACTIVATE',
    REMOVE     : 'BRANCH_SAVE_CREATE',
  },
  STATUS : {
    SUCCESS : 'BRANCH_STATUS_SUCCESS',
    REQUEST : 'BRANCH_STATUS_REQUEST',
    FAILED  : 'BRANCH_STATUS_FAILED',
  },
}

// CODE: Hierarchy

const HIERARCHY = {
  SEND   : {
    FETCH   : 'HIERARCHY_SEND_FETCH',
    REPLACE : 'HIERARCHY_SEND_MODIFY',
  },
  SAVE   : {
    REPLACE : 'HIERARCHY_SAVE_REPLACE',
    ADDAT   : 'HIERARCHY_SAVE_ADDAT',
  },
  STATUS : {
    SUCCESS : 'HIERARCHY_STATUS_SUCCESS',
    REQUEST : 'HIERARCHY_STATUS_REQUEST',
    FAILED  : 'HIERARCHY_STATUS_FAILED',
  },
}

// CODE: Settings

const SETTINGS = {
  SEND   : {
    FETCH  : 'SETTINGS_SEND_FETCH',
    MODIFY : 'SETTINGS_SEND_MODIFY',
  },
  SAVE   : {
    REPLACE : 'SETTINGS_SAVE_REPLACE',
    MODIFY  : 'SETTINGS_SAVE_MODIFY',
  },
  STATUS : {
    SUCCESS : 'SETTINGS_STATUS_SUCCESS',
    REQUEST : 'SETTINGS_STATUS_REQUEST',
    FAILED  : 'SETTINGS_STATUS_FAILED',
  },
}

export { MAIN, JOURNAL, ACCOUNT, BRANCH, HIERARCHY, SETTINGS }
